issue #14
anitab-org/stem-diverse-tv-cms pull request #17
Opened 2021-02-06 21:07 UTC by prachi237

added reporting guidelines

### Description

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-02-07 10:26 UTC, annabauza commented on .github/REPORTING_GUIDLINES.md
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision of the working group, contact the Systers' Open Source Board at techprogs@anitab.org with your appeal and the board wil
@mayburgos is this a real address techprogs@anitab.org ?

2021-02-07 22:33 UTC, prachi237 commented on .github/REPORTING_GUIDLINES.md
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision of the working group, contact the Systers' Open Source Board at techprogs@anitab.org with your appeal and the board wil
@annabauza ,  Ma,am  am  I supposed to make any other changes

2021-02-08 08:12 UTC, annabauza commented on .github/REPORTING_GUIDLINES.md
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision of the working group, contact the Systers' Open Source Board at techprogs@anitab.org with your appeal and the board wil
Yes this email address no longer exists. Please replace with opensource@anitab.org

2021-02-08 08:13 UTC, annabauza requested changes
Please replace deprecated email address with actual one.

2021-02-08 08:53 UTC, prachi237 commented on .github/REPORTING_GUIDLINES.md
> +Only permanent resolutions (such as bans) may be appealed. To appeal a decision of the working group, contact the Systers' Open Source Board at techprogs@anitab.org with your appeal and the board wil
I changed the email address . Done

2021-02-08 16:45 UTC, annabauza approved these changes

2021-02-08 16:45 UTC, merged