Add setup & run instructions, technical stack and branches to readme
anitab-org/stem-diverse-tv-cms pull request #32
Opened 2021-02-13 18:08 UTC by Rahulm2310

### Description

Add setup & run instructions, technical stack and branches info to readme.md.
Fixes #26 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2021-02-13 18:08 UTC, Rahulm2310 commented
@annabauza Please review this PR. Thanks 🙂

2021-02-13 21:30 UTC, annabauza requested changes
I have left you small comments :)

2021-02-14 16:48 UTC, Rahulm2310 commented on README.md
>  ## Contact
@annabauza  Isn't it already added below?

2021-02-14 19:42 UTC, annabauza commented on README.md
>  ## Contact
yes you're right :)

2021-02-15 18:20 UTC, Rahulm2310 commented
@annabauza Added the suggested changes and some badges. Please review it 🙂

2021-02-15 21:29 UTC, annabauza approved these changes

2021-02-15 21:29 UTC, merged