updated readme file with correct links
anitab-org/stem-diverse-tv-cms pull request #38
Opened 2021-02-21 20:01 UTC by Joy-FrontEnd

### Description

Fixes #31 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-02-23 11:19 UTC, HeroicHitesh requested changes

2021-02-23 11:19 UTC, HeroicHitesh commented on README.md
> +Please read our [Contributing Guidelines](https://github.com/anitab-org/stem-diverse-tv-cms/blob/master/.github/CONTRIBUTING_GUIDELINES.md), [Code of Conduct](https://github.com/anitab-org/stem-diver
@Joy-FrontEnd You don't need to provide absolute links, IMO it's better to use relative links, so, for Code of Conduct, instead of `https://github.com/anitab-org/stem-diverse-tv-cms/blob/master/.github/CODE_OF_CONDUCT.md` try using `.github/CODE_OF_CONDUCT.md`
If it works fine you can change other links similarly.

cc @annabauza @Rahulm2310

2021-02-23 13:10 UTC, Joy-FrontEnd commented on README.md
> +Please read our [Contributing Guidelines](https://github.com/anitab-org/stem-diverse-tv-cms/blob/master/.github/CONTRIBUTING_GUIDELINES.md), [Code of Conduct](https://github.com/anitab-org/stem-diver
Done. is it okay now? 😐 Learning how to contribute on Github.

2021-02-24 06:53 UTC, HeroicHitesh commented on README.md
> +Please read our [Contributing Guidelines](https://github.com/anitab-org/stem-diverse-tv-cms/blob/master/.github/CONTRIBUTING_GUIDELINES.md), [Code of Conduct](https://github.com/anitab-org/stem-diver
LGTM

2021-02-24 07:02 UTC, HeroicHitesh commented
@Joy-FrontEnd Also, I would recommend you to please go through the documents for whom you updated the links, it will help you learn a lot about contributing to Github. The major things that you can improve in this PR after going through those docs are how you name the PR, how you should write commit-msg, etc.

2021-02-24 17:35 UTC, Rahulm2310 reviewed
Changes Tested 👍 
Result:
Expected behaviour: The links should go to correct files.
Actual behaviour: As expected.
![stem-links-fix](https://user-images.githubusercontent.com/54268438/109041067-a78c0000-76f4-11eb-92f2-883adafee435.gif)

Good Job @Joy-FrontEnd 🎉

2021-02-24 18:19 UTC, Joy-FrontEnd commented
Thank you @Rahulm2310 😀

2021-03-02 20:20 UTC, annabauza approved these changes

2021-03-02 20:20 UTC, merged