Fixed : Registeration & Login on the Hosted App
anitab-org/stem-diverse-tv-cms pull request #40
Opened 2021-02-23 10:50 UTC by chinmaym07

### Description

I have made a .env.sample file & for testing
1) if you are testing it locally you need to set REACT_APP_ENVIRONMENT_CONFIG=local 
2) if you are testing it on the production you need to set REACT_APP_ENVIRONMENT_CONFIG=prod & as CORS issue is not yet solved on the backend [#93](https://github.com/anitab-org/stem-diverse-tv/issues/93) you need to have this [chrome](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=en) extension & enable then test you will be able to register & login to the hosted version.
3) It requires a documentation update on the readme.md about setting the env config.

Fixes #29 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

I have added gif
1) When REACT_APP_ENVIRONMENT_CONFIG is set to local .

![Peek 2021-02-23 15-30](https://user-images.githubusercontent.com/44670961/108831175-c2c11780-75ef-11eb-8c2b-3c888c6e5dfd.gif)

2) When REACT_APP_ENVIRONMENT_CONFIG is set to prod .

![Peek 2021-02-23 15-35](https://user-images.githubusercontent.com/44670961/108832340-6c54d880-75f1-11eb-89ef-8d4b5b53a238.gif)

2021-02-24 14:30 UTC, jalajcodes requested changes
Can you edit the `package.json` file to remove `proxy` as we won't be needing it now after we add CORS on backend

After above change everything LGTM. 😄

2021-02-24 15:26 UTC, chinmaym07 commented
@jalajcodes thanks for the review  .
I have made the required changes as well as added the instructions required for setting it up in the Readme.
If you can review it again .It will be really helpful to me . thanks in advance. 👍🏻  😬

2021-02-25 06:22 UTC, jalajcodes requested changes
Can you amend your commit and remove the `.lock` files as they are unrelated

2021-02-26 20:13 UTC, chinmaym07 commented
@jalajcodes Done . Please have a look .
Can you please test the same locally ?

2021-03-02 20:16 UTC, annabauza requested changes
yarn.lock  should stay

2021-03-03 13:47 UTC, jalajcodes commented
> yarn.lock  should stay

hmm...no problem, I just asked to remove it because there are no new packages installed or removed in this PR

2021-03-10 06:50 UTC, annabauza approved these changes

2021-03-10 06:51 UTC, annabauza commented
@chinmaym07  can you resolve conflicts? Thanks.

2021-03-18 06:31 UTC, jalajcodes commented
@chinmaym07 Any updates?

2021-03-18 06:44 UTC, chinmaym07 commented
> @chinmaym07 Any updates?
> 

Yes will resolve it by today .. :+1:

2021-03-19 13:15 UTC, chinmaym07 commented
I was testing someone else PR & forgot to unstage those unnecessary changes & accidentally made those additional changes & therefore removed those in the second commit. Sorry for the trouble !!

2021-03-20 07:41 UTC, annabauza commented
> > yarn.lock  should stay
> 
> hmm...no problem, I just asked to remove it because there are no new packages installed or removed in this PR

In meaning we do not delete that file. But if there are unintentional changes those changes should be removed.

2021-03-20 07:42 UTC, annabauza commented
> I was testing someone else PR & forgot to unstage those unnecessary changes & accidentally made those additional changes & therefore removed those in the second commit. Sorry for the trouble !!
> 

Your pr deletes 17k lines of code...?

2021-03-20 09:00 UTC, annabauza requested changes
@chinmaym07 can you please address my questions and let's make it ready ASAP. This is a massive blocker. Thank you.

2021-03-20 09:29 UTC, chinmaym07 commented on src/pages/Login.tsx
> -                        </FormControl>
That's a part of another pr .. I was testing #39 . while testing I forgot to unstage the changes in my pr ..
That's why remove this in the second commit,

2021-03-20 09:34 UTC, chinmaym07 commented
I will open another pr by today itself as I know that's a blocker .. will complete it by today ... 
I am really sorry for the trouble that is caused by me . @annabauza

2021-03-20 10:00 UTC, annabauza commented
You helping no trouble. Thank you.

2021-03-20 11:09 UTC, closed without merging