chore: add config.yml for welcome bot
anitab-org/stem-diverse-tv-cms pull request #44
Opened 2021-03-10 08:30 UTC by nlok5923

### Description

this pull request add config.yml file for welcome bot

Fixes #42 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- config.yml file for welcome bot

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2021-03-13 01:17 UTC, jalajcodes requested changes

2021-03-13 01:17 UTC, jalajcodes commented on .github/workflows/config.yml
> +  Thank you and congrats🎉for opening your very first issue in this project. AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸 Please adhere to our [Code of
We have a Code of conduct file in this repo too, maybe link that instead.

2021-03-13 01:17 UTC, jalajcodes commented on .github/workflows/config.yml
> +  You may submit a PR if you like. If you want to report a bug🐞 please follow our [ISSUE_TEMPLATE.md](https://github.com/anitab-org/.github/tree/main/.github/ISSUE_TEMPLATE). Also make sure you inclu
Same here

2021-03-13 01:17 UTC, jalajcodes commented on .github/workflows/config.yml
> +  Thank you and congrats🎉 for opening your first pull request.✨ AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸Please adhere to our [Code of Conduct](htt
Here too 😅

2021-03-13 02:41 UTC, nlok5923 commented on .github/workflows/config.yml
> +  Thank you and congrats🎉 for opening your first pull request.✨ AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸Please adhere to our [Code of Conduct](htt
addressed

2021-03-13 02:41 UTC, nlok5923 commented on .github/workflows/config.yml
> +  You may submit a PR if you like. If you want to report a bug🐞 please follow our [ISSUE_TEMPLATE.md](https://github.com/anitab-org/.github/tree/main/.github/ISSUE_TEMPLATE). Also make sure you inclu
addressed

2021-03-13 02:41 UTC, nlok5923 commented on .github/workflows/config.yml
> +  Thank you and congrats🎉for opening your very first issue in this project. AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸 Please adhere to our [Code of
addressed

2021-03-13 02:42 UTC, nlok5923 commented
@annabauza please review this pr.

2021-03-22 18:14 UTC, Rahulm2310 commented on .github/workflows/config.yml
> +  You may submit a PR if you like. If you want to report a bug🐞 please follow our [ISSUE_TEMPLATE.md](https://github.com/anitab-org/stem-diverse-tv-cms/tree/master/.github/ISSUE_TEMPLATE). Also make
As there is already an issue open for deleting the ISSUE_TEMPLATE (#46), you can update the link to the issue template under [.github](https://github.com/anitab-org/.github) repo.

2021-03-23 03:30 UTC, nlok5923 commented on .github/workflows/config.yml
> +  You may submit a PR if you like. If you want to report a bug🐞 please follow our [ISSUE_TEMPLATE.md](https://github.com/anitab-org/stem-diverse-tv-cms/tree/master/.github/ISSUE_TEMPLATE). Also make
yeah sure thanks @Rahulm2310

2021-03-30 17:54 UTC, Rahulm2310 approved these changes
LGTM 💯

2021-03-31 09:31 UTC, jalajcodes approved these changes

2021-04-02 08:45 UTC, annabauza approved these changes

2021-04-02 08:45 UTC, merged